version: '3.8'

services:
  minio:
    image: minio/minio
    container_name: smart-vision-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin123@sm123
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"


  rabbitmq:
    image: rabbitmq:3-management
    container_name: smart-vision-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin@sm123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  mysql:
    image: mysql:8.0
    container_name: smart-vision-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root@sm123
      - MYSQL_DATABASE=smartvision
    volumes:
      - mysql_data:/var/lib/mysql

  nginx:
    image: nginx:latest
    container_name: smart-vision-nginx
    ports:
      - "7900:80"
      - "7943:443"
    volumes:
      - nginx_conf:/etc/nginx/conf.d
      - nginx_logs:/var/log/nginx

volumes:
  rabbitmq_data: 
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/rabbitmq/data
      o: bind

  minio_data:
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/minio/data
      o: bind

  mysql_data:
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/mysql/data
      o: bind

  nginx_conf:
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/nginx/conf
      o: bind

  nginx_logs: 
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/nginx/logs
      o: bind
