version: '3.8'

services:
  smart-vision-minio:
    image: minio/minio
    container_name: smart-vision-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=Qw7!pL9z@eX2#vRt
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - smart-vision-network

  smart-vision-rabbitmq:
    image: rabbitmq:3-management
    container_name: smart-vision-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=G7!kLp2#zQw9@xVt
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

    networks:
      - smart-vision-network

  smart-vision-mysql:
    image: mysql:8.0
    container_name: smart-vision-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=R8!kLp2#zQw9@xVt
      - MYSQL_DATABASE=smartvision
      - MYSQL_USER=smartvision
      - MYSQL_PASSWORD=DvZ26&v%4UGEY&aR
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - smart-vision-network


  smart-vision-nginx:
    image: nginx:latest
    container_name: smart-vision-nginx
    ports:
      - "7900:80"
      - "7943:443"
    volumes:
      - nginx_conf:/etc/nginx/conf.d
      - nginx_logs:/var/log/nginx
    networks:
      - smart-vision-network


volumes:
  rabbitmq_data: 
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/rabbitmq/data
      o: bind

  minio_data:
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/minio/data
      o: bind

  mysql_data:
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/mysql/data
      o: bind

  nginx_conf:
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/nginx/conf
      o: bind

  nginx_logs: 
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/nginx/logs
      o: bind
# 网络定义部分
networks:
  smart-vision-network:  # 自定义网络名称
    driver: bridge  # 网络驱动类型
    ipam:  # IP地址管理配置
      config:
        - subnet: 172.26.0.0/16  # 子网设置
          gateway: 172.26.0.1    # 网关
